import { Staatliches, Outfit } from "next/font/google";
import "./globals.css";
import 'modern-normalize';
import Header from "./components/header";
import Footer from "./components/footer";

const staatliches = Staatliches({
  variable: "--font-title",
  weight: ['400'],
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-info",
  weight: ['200','400','600'],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${staatliches.variable} ${outfit.variable} antialiased`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
